version: "3.9"
services:

  trade:
    profiles: []
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    command: python ./App.py --strategy None
    restart: on-failure

  simplekeras:
    container_name: biml-simplekeras
    extends:
      service: trade
    command: python ./App.py --config simplekerasstrategy.yaml

  lstm:
    container_name: biml-lstm
    extends:
      service: trade
    command: python ./App.py --config lstmstrategy.yaml

  lstm2:
    container_name: biml-lstm2
    extends:
      service: trade
    command: python ./App.py --config lstmstrategy2.yaml
