version: "3.9"
services:
  downloader:
    container_name: biml-downloader
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./biml/data:/biml/data
    command: python ./Downloader.py
    restart: on-failure
