version: "3.9"
services:

  trade:
    profiles: []
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./pytrade2/cfg:/pytrade2/cfg
    command: python ./App.py --strategy None
    restart: on-failure

  simplekeras:
    container_name: pytrade2-simplekeras
    extends:
      service: trade
    command: python ./App.py --pytrade2.strategy SimpleKerasStrategy

  lstm:
    container_name: pytrade2-lstm
    extends:
      service: trade
    command: python ./App.py --pytrade2.strategy LSTMStrategy

  lstm2:
    container_name: pytrade2-lstm2
    extends:
      service: trade
    command: python ./App.py --pytrade2.strategy LSTMStrategy2
