version: "3.9"
services:

  trade:
    profiles: []
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./pytrade2/cfg:/pytrade2/cfg
    command: python ./App.py --strategy None
    restart: on-failure

  simplekerasstrategy:
    container_name: simplekerasstrategy
    extends:
      service: trade
    command: python ./App.py --pytrade2.strategy SimpleKerasStrategy

  lstmstrategy:
    container_name: lstmstrategy
    extends:
      service: trade
    command: python ./App.py --pytrade2.strategy LSTMStrategy

  lstmstrategy2:
    container_name: lstmstrategy2
    extends:
      service: trade
    command: python ./App.py --pytrade2.strategy LSTMStrategy2
